# .github/workflows/ci.yml
name: Express.js CI

on:
  push:
    branches: [ main, unittest/backend ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write         # Required for Check Run creation
  pull-requests: write  # Required for PR comments


jobs:
  unittest-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: backend
        run: npm install -D

      - name: Run tests with Testcontainers
        working-directory: backend
        run: npm test
        continue-on-error: true 

      - name: Publish Unit Test Results (Check Run)
        uses: dorny/test-reporter@v1
        if: success() || failure() # Runs unless the workflow was cancelled/skipped
        with:
          name: Jest Tests
          path: backend/reports/junit.xml
          reporter: jest-junit
          fail-on-error: true # This fails the specific check run if tests failed

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: backend/coverage/lcov-report

      - name: Read Jest JSON results
        id: read_results
        run: |
          echo "json=$(cat jest-report/results.json | jq -r tostring)" >> $GITHUB_OUTPUT

      - name: Create PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: jest-report/results.json