# .github/workflows/ci.yml
name: Express.js CI

on:
  push:
    branches: [ main, unittest/backend ]
  pull_request:
    branches: [ main ]

jobs:
  unittest-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: backend
        run: npm install -D

      - name: Run tests with Testcontainers
        working-directory: backend
        run: npm test